<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Shader\OverlayContrastEffect.ps" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Shader\NegativeEffect.ps" />
    <Resource Include="Shader\AddEffect.ps" />
    <Resource Include="Shader\OverlayContrastEffect.ps" />
  </ItemGroup>

</Project>
